// Imports
//import './foreach';
//import './map';
//import './filter';
//import './find';
//import './everysome';
//import './reduce';
//import './constlet';
//import './arrowfunctions';
//import './objectliterals';
//import './def-function-arg';
//import './rest-spread';
//import './destructuring';
//import './classes';
import './_generators';